[theme]
    isDark = true
    [theme.color]
        front = 0xffEDEDED
        back = 0xff171717
        primary = 0xff66DE93
        primaryVariant = 0xff66DE93
        secondary = 0xff185ADB
        success = 0xff81B214
        warning = 0xffFFCC29
        error = 0xffDA0037
[window]
    widthP = 85
    heightP = 85
    alwaysOnTop = true
