[theme]
    isDark = true
    [theme.color]
        front = 0xffcccccc
        back = 0xff0c0c0c
        primary = 0xff2962ff
        secondary = 0xffd500f9
        success = 0xff00c853
        warning = 0xffffd600
        error = 0xffff1744
[window]
    widthP = 85
    heightP = 85
    alwaysOnTop = true
